"""empty message

Revision ID: 0cef6237fb90
Revises: 77fe4dcac62e
Create Date: 2023-12-27 14:30:41.129519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cef6237fb90'
down_revision = '77fe4dcac62e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_exam_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exam_answer_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_exam_association', schema=None) as batch_op:
        batch_op.drop_column('exam_answer_path')

    # ### end Alembic commands ###
