"""empty message

Revision ID: 2a757869abb5
Revises: b131a2fb4421
Create Date: 2024-01-18 13:07:27.285639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a757869abb5'
down_revision = 'b131a2fb4421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exploits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exploits', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
