"""empty message

Revision ID: 40a70fd1ec59
Revises: 70e96a3bae47
Create Date: 2023-12-26 08:42:18.911778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40a70fd1ec59'
down_revision = '70e96a3bae47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('severity', sa.String(length=20), nullable=True))

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=15), nullable=True))

    with op.batch_alter_table('exploits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usage_guide', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exploits', schema=None) as batch_op:
        batch_op.drop_column('usage_guide')

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('ip_address')

    with op.batch_alter_table('cves', schema=None) as batch_op:
        batch_op.drop_column('severity')
        batch_op.drop_column('score')

    # ### end Alembic commands ###
