"""empty message

Revision ID: 5d07594ed355
Revises: 89a08d88580e
Create Date: 2023-12-27 07:31:07.872762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d07594ed355'
down_revision = '89a08d88580e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_exam_association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_constraint('exams_user_id_key', type_='unique')
        batch_op.drop_constraint('exams_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('exams_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_unique_constraint('exams_user_id_key', ['user_id'])

    op.drop_table('user_exam_association')
    # ### end Alembic commands ###
