"""empty message

Revision ID: 77fe4dcac62e
Revises: dea85490921f
Create Date: 2023-12-27 08:41:42.512117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77fe4dcac62e'
down_revision = 'dea85490921f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_results')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exam_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('submission_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name='exam_results_exam_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='exam_results_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='exam_results_pkey')
    )
    # ### end Alembic commands ###
