"""empty message

Revision ID: b131a2fb4421
Revises: cc26b8c772ba
Create Date: 2024-01-10 20:52:35.996603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b131a2fb4421'
down_revision = 'cc26b8c772ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exploits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exploit_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exploits', schema=None) as batch_op:
        batch_op.drop_column('exploit_name')

    # ### end Alembic commands ###
