"""empty message

Revision ID: b18e92a24a59
Revises: 54fd23cf4e62
Create Date: 2024-01-10 15:21:54.348652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b18e92a24a59'
down_revision = '54fd23cf4e62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exploits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description_path', sa.String(length=255), nullable=False))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exploits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('description_path')

    # ### end Alembic commands ###
