"""empty message

Revision ID: d9d8f08b2d05
Revises: 2fba210e9b13
Create Date: 2023-12-28 15:46:41.857466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9d8f08b2d05'
down_revision = '2fba210e9b13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=10), nullable=True))

    with op.batch_alter_table('exploits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=10), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('exploits', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('topic')

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
